// This file is auto-generated by update-local-ip.sh
// To change the IP, edit local.env and run: ./update-local-ip.sh
export const environment = {
  production: false,
  // Gateway URL - all API calls go through the gateway
  apiUrl: 'http://192.168.1.136:8080',
  // WebSocket URL - gateway proxies to WebSocket server
  wsUrl: 'ws://192.168.1.136:8080/ws'
};
