#!/bin/bash
# Update all configuration files with the IP from local.env
# Usage: ./update-local-ip.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source local.env to get the IP
if [ -f "$SCRIPT_DIR/local.env" ]; then
    source "$SCRIPT_DIR/local.env"
else
    echo "Error: local.env not found. Create it first."
    exit 1
fi

echo "Updating configuration with LOCAL_IP=$LOCAL_IP"

# Update unified frontend environment
cat > "$SCRIPT_DIR/web/src/environments/environment.ts" << EOF
// This file is auto-generated by update-local-ip.sh
// To change the IP, edit local.env and run: ./update-local-ip.sh
export const environment = {
  production: false,
  // Gateway URL - all API calls go through the gateway
  apiUrl: 'http://${LOCAL_IP}:8080',
  // WebSocket URL - gateway proxies to WebSocket server
  wsUrl: 'ws://${LOCAL_IP}:8080/ws'
};
EOF
echo "Updated: web/src/environments/environment.ts"

# Update mobile environment
cat > "$SCRIPT_DIR/mobile/src/environments/environment.ts" << EOF
// This file is auto-generated by update-local-ip.sh
// To change the IP, edit local.env and run: ./update-local-ip.sh
export const environment = {
  production: false,
  apiUrl: 'http://${LOCAL_IP}:8080/api'
};
EOF
echo "Updated: mobile/src/environments/environment.ts"

echo ""
echo "Done! Backend services will pick up LOCAL_IP from environment."
echo "Make sure to run: source local.env"
echo "Before starting backend services."
