ALTER TABLE roles ADD COLUMN active BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE payment_types ADD COLUMN active BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE client_types ADD COLUMN active BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE allergens ADD COLUMN active BOOLEAN NOT NULL DEFAULT true;
